# Generated by Django 3.2.18 on 2025-07-05 03:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kesmmwad',
            fields=[
                ('KesmNo', models.IntegerField()),
                ('ZamanNo', models.IntegerField()),
                ('MadaNo', models.CharField(max_length=11)),
                ('MadaType', models.SmallIntegerField(blank=True, null=True)),
                ('AutoId', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kesmmwad',
            },
        ),
        migrations.CreateModel(
            name='Mwad',
            fields=[
                ('FacNo', models.IntegerField()),
                ('Level', models.SmallIntegerField()),
                ('MadaNo', models.CharField(max_length=11)),
                ('MadaName', models.CharField(blank=True, max_length=50, null=True)),
                ('AddWhdat', models.SmallIntegerField(blank=True, null=True)),
                ('MadaType', models.SmallIntegerField(blank=True, null=True)),
                ('Asbkia', models.CharField(blank=True, max_length=11, null=True)),
                ('Asbkia1', models.CharField(blank=True, max_length=11, null=True)),
                ('Asbkia2', models.CharField(blank=True, max_length=11, null=True)),
                ('NgahDrga', models.FloatField(blank=True, null=True)),
                ('TeacherNo', models.IntegerField(blank=True, null=True)),
                ('MType', models.CharField(blank=True, max_length=10, null=True)),
                ('TeachORNo', models.SmallIntegerField(blank=True, null=True)),
                ('TanzilShart', models.SmallIntegerField(blank=True, null=True)),
                ('BarCode', models.IntegerField(blank=True, null=True)),
                ('AutoId', models.AutoField(primary_key=True, serialize=False)),
                ('MadaNameE', models.CharField(blank=True, max_length=50, null=True)),
                ('MadaNoE', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'mwad',
            },
        ),
        migrations.CreateModel(
            name='StudentDepartment',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentDepartment',
            },
        ),
        migrations.CreateModel(
            name='Tgdidkid',
            fields=[
                ('FacNo', models.IntegerField()),
                ('KidNo', models.CharField(max_length=11)),
                ('FaselNo', models.SmallIntegerField()),
                ('Zamanno', models.IntegerField()),
                ('KesmNo', models.IntegerField()),
                ('Door', models.SmallIntegerField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('TotalNekat', models.FloatField(blank=True, null=True)),
                ('TotalWhdat', models.SmallIntegerField(blank=True, null=True)),
                ('Nesba', models.FloatField(blank=True, null=True)),
                ('Average', models.FloatField(blank=True, null=True)),
                ('IsalNo', models.CharField(blank=True, max_length=11, null=True)),
                ('IsalDate', models.DateField(blank=True, null=True)),
                ('Mahgoba', models.SmallIntegerField(blank=True, null=True)),
                ('TheseMwad', models.TextField(blank=True, null=True)),
                ('Mongz', models.TextField(blank=True, null=True)),
                ('NotMongz', models.TextField(blank=True, null=True)),
                ('WhdatMosgla', models.SmallIntegerField(blank=True, null=True)),
                ('WhdatMoaada', models.SmallIntegerField(blank=True, null=True)),
                ('WhdatMongz', models.SmallIntegerField(blank=True, null=True)),
                ('Lock1', models.SmallIntegerField(blank=True, null=True)),
                ('EntharType', models.SmallIntegerField(blank=True, null=True)),
                ('AddEntharat', models.SmallIntegerField(blank=True, null=True)),
                ('FosolEntharat', models.TextField(blank=True, null=True)),
                ('RepAverage', models.FloatField(blank=True, null=True)),
                ('RepNotMongz', models.TextField(blank=True, null=True)),
                ('RepMongz', models.TextField(blank=True, null=True)),
                ('RepWhdatMongz', models.SmallIntegerField(blank=True, null=True)),
                ('EikafKid', models.SmallIntegerField(blank=True, null=True)),
                ('AutoId', models.AutoField(primary_key=True, serialize=False)),
                ('TasgilType', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('GetDeploma', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'tgdidkid',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='رقم القيد')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'db_table': 'home.student',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('department_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=50)),
                ('courses', models.JSONField()),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.tgdidkid')),
            ],
        ),
    ]
